spring.application.name=task1


spring.datasource.username=root
spring.datasource.password=Micobi12345#

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
